# Getting the COVID-19 data

Download the data

```{r, echo=TRUE, include=TRUE}
url_confirmed = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv"
url_deaths = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv"
url_recovered = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv"

data_confirmed = read.csv(url_confirmed, header=FALSE)
data_deaths = read.csv(url_deaths, header=FALSE)
data_recovered = read.csv(url_recovered, header=FALSE)
```

Process the data

```{r, echo=TRUE, include=TRUE}
process_dat = function(data){
    times = as.Date(as.character(data[1,5:ncol(data)]), format="%m/%d/%y")
    all_regions = data[2:nrow(data), 2]
    regions = unique(data[2:nrow(data), 2])
    all_num = apply(as.matrix(data[2:nrow(data), 5:ncol(data)]), 2, as.numeric)
    num = lapply(1:length(times), function(col){
        sapply(regions, function(reg){
            sum(all_num[all_regions == reg, col])
        })
    })
    data_mat = Reduce(f=cbind, x=num)
    colnames(data_mat) = cumsum(as.numeric(c(0, diff(times))))
    return(data_mat)
}

data_confirmed = process_dat(data_confirmed)
data_deaths = process_dat(data_deaths)
data_recovered = process_dat(data_recovered)
```

Save the data

```{r, echo=TRUE, include=TRUE}
write.csv(data_confirmed, file="output/data_confirmed.csv")
write.csv(data_deaths, file="output/data_deaths.csv")
write.csv(data_recovered, file="output/data_recovered.csv")
```
