# Statistics in the Nordic countries

Read the data

```{r, echo=TRUE, include=TRUE}
data_confirmed = read.csv("output/data_confirmed.csv", header=FALSE)
data_deaths = read.csv("output/data_deaths.csv", header=FALSE)
data_recovered = read.csv("output/data_recovered.csv", header=FALSE)

country_list = c("Finland", "Sweden", "Norway", "Denmark", "Iceland")
cols = c("grey", "yellow", "red", "pink", "blue")
```

# Plots {.tabset}

## Total cases

```{r, echo=TRUE, include=TRUE, fig.height=6}
times = as.numeric(data_confirmed[1, 2:ncol(data_confirmed)])
cases = lapply(country_list, function(cou){
    as.numeric(data_confirmed[match(cou,
        data_confirmed[, 1]), 2:ncol(data_confirmed)])
})
max_cases = max(Reduce(x=cases, f=c)) + 20
plot(x=times, y=cases[[1]], ylim = c(0, max_cases),
    col=cols[1], type="l", lwd=4,
    xlab="day", ylab="cases",
    main="Cases in Nordic countries")

for(i in 2:length(country_list)){
    lines(x=times, y=cases[[i]], type="l", col=cols[i], lwd=4)
}

legend(3, max_cases * 0.9,
    legend=country_list, col=cols, lwd=4)
```

## Deaths

```{r, echo=TRUE, include=TRUE, fig.height=6}
times = as.numeric(data_deaths[1, 2:ncol(data_confirmed)])
deaths = lapply(country_list, function(cou){
    as.numeric(data_deaths[match(cou,
        data_confirmed[, 1]), 2:ncol(data_confirmed)])
})
max_deaths = max(Reduce(x=deaths, f=c)) + 20
plot(x=times, y=deaths[[1]], ylim = c(0, max_deaths),
    col=cols[1], type="l", lwd=4,
    xlab="day", ylab="deaths",
    main="Deaths in Nordic countries")

for(i in 2:length(country_list)){
    lines(x=times, y=deaths[[i]], type="l", col=cols[i], lwd=4)
}

legend(3, max_deaths * 0.9,
    legend=country_list, col=cols, lwd=4)
```

## Recovered

```{r, echo=TRUE, include=TRUE, fig.height=6}
times = as.numeric(data_recovered[1, 2:ncol(data_confirmed)])
recovered = lapply(country_list, function(cou){
    as.numeric(data_recovered[match(cou,
        data_confirmed[, 1]), 2:ncol(data_confirmed)])
})

max_recovered = max(Reduce(x=recovered, f=c)) + 20
plot(x=times, y=recovered[[1]], ylim = c(0, max_recovered),
    col=cols[1], type="l", lwd=4,
    xlab="day", ylab="recovered",
    main="Recoveries in Nordic countries")

for(i in 2:length(country_list)){
    lines(x=times, y=recovered[[i]], type="l", col=cols[i], lwd=4)
}

legend(3, max_recovered * 0.9,
    legend=country_list, col=cols, lwd=4)
```

# Analysis Metadata
