---
title: Normalization and Variance Modelling
---

```{r setup}
source("src/env.R")
sce.nest <- readRDS("output/nestorowa_quality_control_sce.RDS")
```

# Normalization

```{r normalization}
library(scran)
set.seed(101000110)
clusters <- quickCluster(sce.nest)
sce.nest <- computeSumFactors(sce.nest, clusters=clusters)
sce.nest <- logNormCounts(sce.nest)
```

We examine some key metrics for the distribution of size factors, and compare it to the library sizes as a sanity check.

```{r}
summary(sizeFactors(sce.nest))
```

```{r unref-nest-norm, fig.cap="Relationship between the library size factors and the deconvolution size factors in the Nestorowa HSC dataset."}
plot(librarySizeFactors(sce.nest), sizeFactors(sce.nest), pch=16,
    xlab="Library size factors", ylab="Deconvolution factors", log="xy")
```

# Variance modelling

We use the spike-in transcripts to model the technical noise as a function of the mean.

```{r variance-modelling}
set.seed(00010101)
dec.nest <- modelGeneVarWithSpikes(sce.nest, "ERCC")
top.nest <- getTopHVGs(dec.nest, prop=0.1)
```

```{r unref-nest-var, fig.cap="Per-gene variance as a function of the mean for the log-expression values in the Nestorowa HSC dataset. Each point represents a gene (black) with the mean-variance trend (blue) fitted to the spike-ins (red)."}
plot(dec.nest$mean, dec.nest$total, pch=16, cex=0.5,
    xlab="Mean of log-expression", ylab="Variance of log-expression")
curfit <- metadata(dec.nest)
curve(curfit$trend(x), col='dodgerblue', add=TRUE, lwd=2)
points(curfit$mean, curfit$var, col="red")
```

```{r export}
saveRDS(sce.nest,"output/nestorowa_normalization_sce.RDS")
saveRDS(top.nest,"output/nestorowa_normalization_top.RDS")
saveRDS(dec.nest,"output/nestorowa_normalization_dec.RDS")
```

